theme: jekyll-theme-minimal
title: NLP Lab
logo: /assets/img/logo-iu-red.png
description: The Natural Language Processing Lab and Quantum AI Study Group
show_downloads: false
google_analytics: G-H2EHQ4SEQF
